# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8287567ef9429987318598c42cd33279685efadf185a9ed86a4c4e9d87497a2bbb5b1aa0666bef8ac0f6b00f51993d28b1a836bbec974f0c2a3e8d0f091e8f9

test:
  secret_key_base: b0c13ae35b9efe4c17f928378133371cc32f3a09bf113c93dcfe9f5737d039430ad945bd4ab30d9e7ff5485a68a794d8e33e15fc40618107fcf2f562bccf5dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
