# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3851c5c9da1aa0adfa819d411d825b2b0dbeb062a1ee7b5d9cae2a730c5254475e6727c8b1fb64d570644abd6cc87c88562c9b1d14ab1a7408b7b6be43dbfacd

test:
  secret_key_base: 1fcdf953c9f6a22f02afe9a3a2b79b53e19b902a4a46cecddccfb6aac4b6e6adf503bc1e2cd6338eb31129506efff6576786ee4e12a5b36d4000f2be7aec49bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
